travis:
  secure:
    BINSTAR_TOKEN: ckIEMiw5vORWHhcOfaP5g5K7RyOCryYCUvn0SUbZTZG4SLe61pu2Fp1kUr+FBRLHRn5zUaNqy8/Ct2TxhaQiWbeXb+qujeATwwTfUFLogO5gyo7Qtbltm31c33GBJFqvfyvNvbd3Nk8SJoLfcT2DyFAZgDRlUf4HUkflpEYA7LwsD3RyGh2Jpl1jAkano25ldRBhb1mbF0v+Xq6SNAZRqpC6gLv0lvEGnk7r+KsFnJaoEF/rSmHvUPVEudEvq8/A+pEmOJJirlT82mj8GgBTRZ6V5aTB07d24VWmBKxa5tDrEuc/6mR28VGn/y4JHInoEq1KS5zOlkU5fbAQl0bpLp3HH3Ym1TZ84atigjjuvyvO6SuztTAz3YdgX8P+WHr6VNmr0Ph4QYYK139IK7y9teGgEVMreTFrCG+pRfym/m2eH8/U5+8Ozqmu2YCJhtca7YCFdBnnYezJHLm6l08Uldtnz/cSFzqDwEVXpgUhaiyIMe601rICg3DTJWYiXYYA13fJRNegl6Iu5mRZxDlStzDc+0v6vhmuNhh+7+O54VZVHNwkNtGxI/mpOtGD7ZymXJruLX4ddKxoWX806JThNr6YR25zrTjCCKvGKw95T5lKWGi6Fju8qxKPnU94ljDxjg19gZvPdkgD/mjaELqerBQREIcZo59HeSMZ+E89xLQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
