travis:
  secure:
    BINSTAR_TOKEN: 0TGlg6k1YGMi+X4dsn2NVegVVdTGGJ4sR/6ykynyjH6xZNhFrrzVwb6UZyjEYn3/Fp0DsrkO8v31cFoIohDt4CS07L/w/tBFCCfxvvlZDvaQBaDnhtLu9I6g0ZAPbypzGj4k/WBIBukaoBGf9FemfbOkVv34Bl4vxpUvpPLeZNY7057CbyPwp8KXc3MD9VX3WMlypiEfFCgLe6RBSeuzJfB5rCh3M7QHBNHa9KY7jD7YFL+l/a7ojVLX11Ibo/+8CB2BYErNgjGC/uBt6bqLMfY4nSwTsm/sorDsL6FPELo+NZOeQh7sQateLH7nr3+wNoy+NARBRy8WQGGVNqaZdQky/z5eF/FUdJRn0tQz0Kw4zfDDfnpDwV6Km6yWcm+RTh6BkyggY9uDGtX95im4BYXn1U8tCH6LaJVKVvirMc+jOuR5huvsT3ScrUIQdgftTiw+LrWivzZyFSao7lBHndiMF0vsf2mCBwvVxaXL9QtteATvOUycsCdZrivnEuoJCs4oTcCiidPv9tsVvqBbYgR/n4sdORjiR9Yg+GA1Mlk54zd+liTBLMF4TYhqphQ4B8nbnRpDorTWzjS3UxsPIPQ0zVKoz4GhvNokgjf0q0skcSI/QJjRAem+WaDwi+Jru13KoR+cTWyg/9i4+/ug7LdU5dHOa9gaTDsgp2v7lSo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
